[world]
kind = "WorldContract"
class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
original_class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
abi = "manifests/sepolia/deployment/abis/dojo-world.json"
address = "0x37c1bb061637b7b264c00658b325d5ef7d4d12bef3850d358f46a27ec60aeb5"
transaction_hash = "0x53ff3d63dd57e2f07c8286be2283ce5744316e8177a5292d84af478577ed324"
seed = "beastslayers-sepolia-2"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "sepolia"
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x5fb7ed5efdb120694ca24b2f07343b8349d99cca58662866d5eda2dbc1e7720"
class_hash = "0x55d065016abf6c69c46fd269920e59875720649a5d212a4e7bc83153bcecbda"
original_class_hash = "0x55d065016abf6c69c46fd269920e59875720649a5d212a4e7bc83153bcecbda"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/sepolia/deployment/abis/contracts/beastslayers-actions-35befdaf.json"
reads = []
writes = [
    "beastslayers-Warrior",
    "beastslayers-Game",
]
init_calldata = []
tag = "beastslayers-actions"
systems = [
    "attack",
    "mega_attack",
]
manifest_name = "beastslayers-actions-35befdaf"

[[models]]
kind = "DojoModel"
class_hash = "0x1abebea2e4b03680a65489f59a101ebb1becf3111d19b2597443323883d9c3c"
original_class_hash = "0x1abebea2e4b03680a65489f59a101ebb1becf3111d19b2597443323883d9c3c"
abi = "manifests/sepolia/deployment/abis/models/beastslayers-Game-28ba25af.json"
tag = "beastslayers-Game"
qualified_path = "beastslayers::models::game"
manifest_name = "beastslayers-Game-28ba25af"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "current_beast"
type = "Beast"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x90e6edf16d1b4425bf1886e6a043cf6b5aebe211a4e05b935e90c85da3b062"
original_class_hash = "0x90e6edf16d1b4425bf1886e6a043cf6b5aebe211a4e05b935e90c85da3b062"
abi = "manifests/sepolia/deployment/abis/models/beastslayers-Warrior-60be6cf8.json"
tag = "beastslayers-Warrior"
qualified_path = "beastslayers::models::warrior"
manifest_name = "beastslayers-Warrior-60be6cf8"

[[models.members]]
name = "address"
type = "ContractAddress"
key = true

[[models.members]]
name = "level"
type = "u32"
key = false

[[models.members]]
name = "last_mega_attack"
type = "u64"
key = false

[[models.members]]
name = "score"
type = "u32"
key = false
