kind = "DojoModel"
class_hash = "0x498339c7ddaccfde3fa8c03a8584235d019318c63e4bd9b0971f35b031d095a"
original_class_hash = "0x498339c7ddaccfde3fa8c03a8584235d019318c63e4bd9b0971f35b031d095a"
abi = "manifests/sepolia/base/abis/models/beastslayers-ERC20MetadataModel-bd958e58.json"
tag = "beastslayers-ERC20MetadataModel"
qualified_path = "origami_token::components::token::erc20::erc20_metadata::erc_20_metadata_model"
manifest_name = "beastslayers-ERC20MetadataModel-bd958e58"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "ByteArray"
key = false

[[members]]
name = "symbol"
type = "ByteArray"
key = false

[[members]]
name = "decimals"
type = "u8"
key = false

[[members]]
name = "total_supply"
type = "u256"
key = false
