kind = "DojoModel"
class_hash = "0x132dc763dcacaa091daa816aeb77b5bd9d9fbc9db939f1efa476f4f0ad2c84e"
original_class_hash = "0x132dc763dcacaa091daa816aeb77b5bd9d9fbc9db939f1efa476f4f0ad2c84e"
abi = "manifests/sepolia/base/abis/models/beastslayers-ERC20BalanceModel-48c68ab0.json"
tag = "beastslayers-ERC20BalanceModel"
qualified_path = "origami_token::components::token::erc20::erc20_balance::erc_20_balance_model"
manifest_name = "beastslayers-ERC20BalanceModel-48c68ab0"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "account"
type = "ContractAddress"
key = true

[[members]]
name = "amount"
type = "u256"
key = false
