kind = "DojoModel"
class_hash = "0x90e6edf16d1b4425bf1886e6a043cf6b5aebe211a4e05b935e90c85da3b062"
original_class_hash = "0x90e6edf16d1b4425bf1886e6a043cf6b5aebe211a4e05b935e90c85da3b062"
abi = "manifests/sepolia/base/abis/models/beastslayers-Warrior-60be6cf8.json"
tag = "beastslayers-Warrior"
qualified_path = "beastslayers::models::warrior"
manifest_name = "beastslayers-Warrior-60be6cf8"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "level"
type = "u32"
key = false

[[members]]
name = "last_mega_attack"
type = "u64"
key = false

[[members]]
name = "score"
type = "u32"
key = false
