tag = "beastslayers-actions"
writes = [
    "beastslayers-Warrior",
    "beastslayers-Game",
    "beastslayers-ERC20MetadataModel",
    "beastslayers-ERC20BalanceModel",
    "beastslayers-ERC20AllowanceModel",
    "beastslayers-ERC20BridgeableModel",
    "beastslayers-InitializableModel",
]
