kind = "DojoModel"
class_hash = "0x5f989f1870f762d1d3beba9233c5b425b78b8ea323469242b7f6277232f6499"
original_class_hash = "0x5f989f1870f762d1d3beba9233c5b425b78b8ea323469242b7f6277232f6499"
abi = "manifests/dev/base/abis/models/beastslayers-ERC20MetadataModel-bd958e58.json"
tag = "beastslayers-ERC20MetadataModel"
qualified_path = "beastslayers::tokens::thing::erc_20_metadata_model"
manifest_name = "beastslayers-ERC20MetadataModel-bd958e58"

[[members]]
name = "token"
type = "ContractAddress"
key = true

[[members]]
name = "name"
type = "ByteArray"
key = false

[[members]]
name = "symbol"
type = "ByteArray"
key = false

[[members]]
name = "decimals"
type = "u8"
key = false

[[members]]
name = "total_supply"
type = "u256"
key = false
