kind = "DojoModel"
class_hash = "0x7d4ca4cf1799106afeb22558fa34f4d9be7bef8c5d8019c137d43faa38f3151"
original_class_hash = "0x7d4ca4cf1799106afeb22558fa34f4d9be7bef8c5d8019c137d43faa38f3151"
abi = "manifests/dev/base/abis/models/beastslayers-Warrior-60be6cf8.json"
tag = "beastslayers-Warrior"
qualified_path = "beastslayers::models::warrior"
manifest_name = "beastslayers-Warrior-60be6cf8"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "level"
type = "u32"
key = false
