kind = "DojoModel"
class_hash = "0x6d8610c75a9890781702c7e7df035ad4fd3e94acd17be0cf7ca1d5649b7aea4"
original_class_hash = "0x6d8610c75a9890781702c7e7df035ad4fd3e94acd17be0cf7ca1d5649b7aea4"
abi = "manifests/dev/base/abis/models/beastslayers-Warrior-60be6cf8.json"
tag = "beastslayers-Warrior"
qualified_path = "beastslayers::models::warrior"
manifest_name = "beastslayers-Warrior-60be6cf8"

[[members]]
name = "address"
type = "ContractAddress"
key = true

[[members]]
name = "level"
type = "u32"
key = false

[[members]]
name = "score"
type = "u32"
key = false

[[members]]
name = "unclaimed_tokens"
type = "u256"
key = false
