kind = "DojoContract"
class_hash = "0x55d065016abf6c69c46fd269920e59875720649a5d212a4e7bc83153bcecbda"
original_class_hash = "0x55d065016abf6c69c46fd269920e59875720649a5d212a4e7bc83153bcecbda"
base_class_hash = "0x0"
abi = "manifests/sepolia/base/abis/contracts/beastslayers-actions-35befdaf.json"
reads = []
writes = []
init_calldata = []
tag = "beastslayers-actions"
systems = [
    "attack",
    "mega_attack",
]
manifest_name = "beastslayers-actions-35befdaf"
