kind = "DojoModel"
class_hash = "0x1abebea2e4b03680a65489f59a101ebb1becf3111d19b2597443323883d9c3c"
original_class_hash = "0x1abebea2e4b03680a65489f59a101ebb1becf3111d19b2597443323883d9c3c"
abi = "manifests/mainnet/base/abis/models/beastslayers-Game-28ba25af.json"
tag = "beastslayers-Game"
qualified_path = "beastslayers::models::game"
manifest_name = "beastslayers-Game-28ba25af"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "current_beast"
type = "Beast"
key = false
