kind = "DojoContract"
class_hash = "0x54f0cdc91e79a0d77dc2f7785a0f4cb2758ec6610ed0bf3f81d590dcaf5734a"
original_class_hash = "0x54f0cdc91e79a0d77dc2f7785a0f4cb2758ec6610ed0bf3f81d590dcaf5734a"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/beastslayers-actions-35befdaf.json"
reads = []
writes = []
init_calldata = []
tag = "beastslayers-actions"
systems = [
    "attack",
    "mega_attack",
]
manifest_name = "beastslayers-actions-35befdaf"
