kind = "DojoContract"
class_hash = "0x4567c88d60a7782f1c5edf93d60abe19fc6136438d30ff0248d301efabbd6a5"
original_class_hash = "0x4567c88d60a7782f1c5edf93d60abe19fc6136438d30ff0248d301efabbd6a5"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/beastslayers-Thing-6a24670b.json"
reads = []
writes = []
init_calldata = []
tag = "beastslayers-Thing"
systems = ["initializer"]
manifest_name = "beastslayers-Thing-6a24670b"
