kind = "DojoContract"
class_hash = "0x7896d9546dc21ad4349a3e79ee7186031935a0224dec75f493f71d898a32e8a"
original_class_hash = "0x7896d9546dc21ad4349a3e79ee7186031935a0224dec75f493f71d898a32e8a"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/beastslayers-actions-35befdaf.json"
reads = []
writes = []
init_calldata = []
tag = "beastslayers-actions"
systems = [
    "attack",
    "claim_tokens",
]
manifest_name = "beastslayers-actions-35befdaf"
