kind = "DojoContract"
class_hash = "0x20692898e0d96a3144ec80e882fc675b15b0616bb728fe30c34f57770edd81"
original_class_hash = "0x20692898e0d96a3144ec80e882fc675b15b0616bb728fe30c34f57770edd81"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/beastslayers-actions-35befdaf.json"
reads = []
writes = []
init_calldata = []
tag = "beastslayers-actions"
systems = ["attack"]
manifest_name = "beastslayers-actions-35befdaf"
